---
jenkins_repo_url: https://pkg.jenkins.io/debian-stable
jenkins_repo_key_url: https://pkg.jenkins.io/debian-stable/jenkins.io-2026.key
jenkins_repo_key_path: /usr/share/keyrings/jenkins-keyring.asc
jenkins_java_package: "{{ 'openjdk-21-jre' if (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version | int >= 24) else 'openjdk-17-jre' }}"
jenkins_http_port: 8080
jenkins_listen_address: 127.0.0.1
jenkins_home: /var/lib/jenkins
jenkins_plugin_updates_enabled: true
jenkins_plugin_update_timeout: 300
jenkins_plugin_update_metadata_expiration: 3600
