# Configuration for the DNS config role
cloudflare:
  enabled: true
  email: YOUR EMAIL
  api_key: YOUR API KEY

# Configuration for the hestia role
hestia_admin_mail: YOUR EMAIL
hestia_admin_pw: ADMIN PASSWORD

# Sql Server configuration
mssql:
  sa_password: your strong password
  pid: express  # evaluation, developer, express, web, standard, enterprise, or your 25 digit product key

# Keycloak configuration
keycloak:
  version: version
  user: keycloak user
  home: home directory
  db_name: db name
  db_user: db user
  db_password: db password
  admin_user: admin user
  admin_password: admin password
  domain_name: domain name
  email_for_ssl: email for ssl
