---

- hosts: all
  roles:
    - maintain

- hosts: hestia
  roles:
    - hestia

- hosts: dotnet
  roles:
    - dotnet

- hosts: sqlserver
  roles:
    - sqlserver

- hosts: keycloak
  roles:
    - keycloak