---
    
- hosts: all
  roles:
    - maintain

- hosts: hestia
  roles:
    - hestia

- hosts: dotnet
  roles:
    - dotnet

- hosts: sqlserver
  roles:
    - sqlserver

- hosts: keycloak
  roles:
    - keycloak

- hosts: jenkins
  vars:
    jenkins_plugin_updates_enabled: false
  roles:
    - jenkins

- hosts: smtp_relay
  roles:
    - smtp-relay

- hosts: coolify
  roles:
    - coolify

- hosts: imgproc
  roles:
    - img-proc
