---
- name: daemon-reload
  become: true
  systemd:
    daemon_reload: true

- name: restart fail2ban
  become: true
  service:
    name: fail2ban
    state: restarted

- name: reload fail2ban
  become: true
  command: fail2ban-client reload
  changed_when: true
