- name: Update user SSH keys (exclusive - removes unknown keys)
  ansible.posix.authorized_key:
    user: '{{ ansible_user }}'
    key: "{% for f in lookup('fileglob', 'user-keys/*', wantlist=True) %}{{ lookup('file', f) }}\n{% endfor %}"
    state: present
    exclusive: true