---
# tasks file for hestiacp

- name: "Install HestiaCP"
  import_tasks: install.yml

- name: "Apply nginx restart guard"
  import_tasks: nginx-guard.yml

- name: "Configure mail policy"
  import_tasks: mail-policy.yml

- name: "Configure Fail2Ban"
  import_tasks: fail2ban.yml

- name: "Configure backups"
  import_tasks: backup.yml
