---
- name: A DNS records
  community.general.cloudflare_dns:
    zone: "manitra.net"
    type: "A"
    record: "{{ item.record }}"
    value: "{{ item.value }}"
    solo: true
    state: "present"
    account_email: "{{ cloudflare.email }}"
    account_api_key: "{{ cloudflare.api_key }}"
  loop: "{{ A }}"
  when: cloudflare.enabled

- name: AAAA DNS records
  community.general.cloudflare_dns:
    zone: "manitra.net"
    type: "AAAA"
    record: "{{ item.record }}"
    value: "{{ item.value }}"
    solo: true
    state: "present"
    account_email: "{{ cloudflare.email }}"
    account_api_key: "{{ cloudflare.api_key }}"
  loop: "{{ AAAA }}"
  when: cloudflare.enabled

- name: CNAME DNS records
  community.general.cloudflare_dns:
    zone: "manitra.net"
    type: "CNAME"
    record: "{{ item.record }}"
    value: "{{ item.value }}"
    state: "present"
    account_email: "{{ cloudflare.email }}"
    account_api_key: "{{ cloudflare.api_key }}"
  loop: "{{ CNAME }}"
  when: cloudflare.enabled
