---
- name: Load config file
  include_vars: .config.yml

- name: Define A DNS record for vps01
  community.general.cloudflare_dns:
    zone: "manitra.net"
    type: "A"
    record: "vps01"
    value: "85.215.184.231"
    ttl: 1
    state: "present"
    account_email: "{{ cloudflare.email }}"
    account_api_key: "{{ cloudflare.api_key }}"