A:
  - record: vps03
    value: 51.75.203.179
  - record: vps06
    value : 5.135.152.108
  - record: vps11
    value: 49.13.231.102

CNAME:
  - record: '@'
    value: vps03.manitra.net
  - record: www
    value: vps03.manitra.net
  - record: merge
    value: vps03.manitra.net