A:
  - record: vps03
    value: 51.75.203.179
  - record: vps04
    value: 51.83.75.177
  - record: vps06
    value : 5.135.152.108
  - record: vps11
    value: 49.13.231.102
  - record: vps12
    value: 23.88.51.61
  - record: vps13
    value: 13.247.181.158

AAAA:
  - record: vps04
    value: "2001:41d0:367:894::1"
  - record: vps11
    value: "2a01:4f8:1c19:e2eb::1"
  - record: vps12
    value: "2a01:4f8:1c19:2db::1"

CNAME:
  - record: '@'
    value: vps03.manitra.net
  - record: www
    value: vps03.manitra.net
  - record: merge
    value: vps03.manitra.net
  - record: build
    value: vps12.manitra.net
  - record: coolify
    value: vps11.manitra.net
  - record: '*'
    value: vps11.manitra.net
  - record: auth
    value: vps11.manitra.net
  - record: trading
    value: vps11.manitra.net
  - record: up
    value: vps11.manitra.net
  - record: www.vps03
    value: vps03.manitra.net
  - record: www.vps06
    value: vps06.manitra.net
  - record: mail
    value: vps03.manitra.net

MX:
  - record: '@'
    value: route1.mx.cloudflare.net
    priority: 49
  - record: '@'
    value: route2.mx.cloudflare.net
    priority: 21
  - record: '@'
    value: route3.mx.cloudflare.net
    priority: 89
  - record: send
    value: feedback-smtp.eu-west-1.amazonses.com
    priority: 10
  - record: hello
    value: mail.hello.manitra.net.
    priority: 10

TXT:
  - record: '@'
    value: "v=DMARC1; p=none; rua=mailto:archive@manitra.net; aspf=r;"
  - record: '@'
    value: "v=spf1 a mx include:_spf.google.com include:_spf.mx.cloudflare.net  ~all"
  - record: '@'
    value: "google-site-verification=ug3DTbAm24136ZaL3jHwG3CVeZrEMFlz8qDBNpknDD0"
  - record: cf2024-1._domainkey
    value: "\"v=DKIM1; h=sha256; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiweykoi+o48IOGuP7GR3X0MOExCUDY/BCRHoWBnh3rChl7WhdyCxW3jgq1daEjPPqoi7sJvdg5hEQVsgVRQP4DcnQDVjGMbASQtrY4WmB1VebF+RPJB2ECPsEDTpeiI5ZyUAwJaVX7r6bznU67g7LvFq35yIo4sdlmtZGV+i0H4cpYH9+3JJ78k\" \"m4KXwaf9xUJCWF6nxeD+qG6Fyruw1Qlbds2r85U9dkNDVAS3gioCvELryh1TxKGiVTkg4wqHTyHfWsp7KD3WQHYJn0RyfJJu6YEmL77zonn7p2SRMvTMP3ZEXibnC9gz3nnhR6wcYL8Q7zXypKTMD58bTixDSJwIDAQAB\""
  - record: resend._domainkey
    value: "\"p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDRMKAREWE1F20ixIxpyS4qPq6ozauq1hNNTOtUb7tLEz6/6F89tXkZ3UrqAdpPJGJZlH9CQCMJKuOkkQ8kwebuGYJ7THSqUMpbkf4LxM1TD0Aa8a9nxlmd3bjKd+JcKHjOe1VxG9IV9Ul9p5aAx/tI/soGknIOKky7riJMtJyc5QIDAQAB\""
  - record: send
    value: "\"v=spf1 include:amazonses.com ~all\""
  - record: hello
    value: "v=spf1 a mx ip4:51.75.203.179 -all"
  - record: hello._dmarc
    value: "v=DMARC1; p=quarantine; pct=100"
  - record: mail._domainkey.hello
    value: "v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArk1r8p6t7VBx+esL2WPjD1QnaZtAyWLo7YmkQdSEKcyqweTQFpNNHAIorTUt/eY1hFT1XE2Hi7yJ0lg/o1maei+sGWVdHgKAtvOZbVYXDRt8Agz6KRFRqTBo328FBYMlP2xqOCa6Q9vIYL+JFYq+WeqEZne2L2yKHl4u8LSn5UsvjlHdntx2lycebkcHnZ26GgQ0ojaDC8F5TGkLv1QV4goM+DVXCN6aGL5sbkRQYDuJ0Dmv2J4mJ2Qt0fVTPxtxNkQvJI/rmP/FzpZ9MWdGnRRY11glOCScpg2ZjDm5iUNbM8hln9/VDe2D2P+fPFwK23iFicOTPs5BOTmQJkhrQQIDAQAB"
