A:
  - record: vps03
    value: 51.75.203.179
  - record: vps06
    value : 5.135.152.108
  - record: vps11
    value: 49.13.231.102

AAAA:
  - record: vps12
    value: "2a01:4f8:1c19:2db::"

CNAME:
  - record: '@'
    value: vps03.manitra.net
  - record: www
    value: vps03.manitra.net
  - record: merge
    value: vps03.manitra.net
  - record: build
    value: vps12.manitra.net