---
- name: Restart Postfix
  ansible.builtin.systemd:
    name: postfix
    enabled: true
    state: restarted

- name: Restart saslauthd
  ansible.builtin.systemd:
    name: saslauthd
    enabled: true
    state: restarted

- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    enabled: true
    state: restarted
