---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Keycloak
  ansible.builtin.systemd:
    name: keycloak
    state: restarted

- name: Reload Nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
