---
relay_enabled: false
relay_postfix_packages:
  - postfix
  - postfix-pcre
  - sasl2-bin
  - libsasl2-modules
  - fail2ban
  - ufw

relay_sasl_config_dir: /etc/postfix/sasl
relay_sasl_config_file: /etc/postfix/sasl/smtpd.conf
relay_sender_login_maps_file: /etc/postfix/sender_login_maps.pcre
relay_sasl_access_file: /etc/postfix/sasl_access.pcre
relay_client_access_dir: /etc/postfix/relay-client-access

relay_users: []
