---
server_hostname: vps13.manitra.net
hestia_generate_ssl: false

hestia_fail2ban_ignore_ips:
  - name: DGU
    ip: 102.16.56.58
  - name: PFI
    ip: 102.16.234.177
hestia_fail2ban_ignore_legacy_files:
  - /etc/fail2ban/jail.d/98-whitelist-102-16-234-177.local

hestia_incremental_backup_cron: true
