---
# handlers file for hestiacp
- name: "reload systemd"
  become: true
  systemd:
    daemon_reload: true

- name: "restart nginx"
  become: true
  service:
    name: nginx
    state: restarted

- name: "reload fail2ban"
  become: true
  ansible.builtin.command: fail2ban-client reload
  changed_when: true

- name: "rebuild and restart exim4"
  become: true
  ansible.builtin.shell: update-exim4.conf && systemctl restart exim4
  args:
    executable: /bin/bash
  changed_when: true

- name: "reboot server"
  reboot:
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 5
    post_reboot_delay: 30
    test_command: whoami
