---
coolify_base_dir: /data/coolify
coolify_source_dir: "{{ coolify_base_dir }}/source"
coolify_env_file: "{{ coolify_source_dir }}/.env"
coolify_cdn_url: https://cdn.coollabs.io/coolify

coolify_app_name: Coolify
coolify_domain: coolify.manitra.net
coolify_registry_url: ghcr.io
coolify_latest_image: latest

coolify_app_bind_address: 127.0.0.1
coolify_app_port: 8083
coolify_soketi_port: 6001
coolify_soketi_metrics_port: 6002

coolify_manage_caddy: true
coolify_caddy_config_dir: /etc/caddy/conf.d
coolify_caddy_config_path: "{{ coolify_caddy_config_dir }}/coolify.caddy"

coolify_ssh_user: root
coolify_ssh_key_path: "{{ coolify_base_dir }}/ssh/keys/id.{{ coolify_ssh_user }}@host.docker.internal"
